import type { ScanRecord } from "../types";

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
}

/** Renders a scan record as a self-contained Markdown report, using only stored analyzer output. */
export function generateMarkdownReport(scan: ScanRecord): string {
  const lines: string[] = [];

  lines.push(`# GitPulse Engineering Health Report`);
  lines.push("");
  lines.push(`**Project:** ${scan.source.label}`);
  lines.push(`**Scan date:** ${formatDate(scan.createdAt)}`);
  lines.push("");
  lines.push(`## Overall Engineering Health`);
  lines.push("");
  lines.push(`**${scan.health.overall ?? "N/A"} / 100** — ${scan.health.bandLabel}`);
  lines.push("");
  lines.push(`## Category Scores`);
  lines.push("");
  lines.push(`| Category | Score |`);
  lines.push(`|---|---|`);
  for (const cat of scan.health.categories) {
    if (cat.weight === 0) continue;
    lines.push(`| ${cat.label} | ${cat.score === null ? "Unavailable" : `${cat.score}/100`} |`);
  }
  lines.push("");

  lines.push(`## Engineering Summary`);
  lines.push("");
  lines.push(scan.engineeringSummary.text);
  lines.push("");

  if (scan.issues.length > 0) {
    lines.push(`## Issues`);
    lines.push("");
    for (const issue of scan.issues) {
      lines.push(`### [${issue.severity.toUpperCase()}] ${issue.title}`);
      lines.push("");
      lines.push(issue.description);
      lines.push("");
      lines.push(`**Evidence:**`);
      for (const e of issue.evidence) lines.push(`- ${e}`);
      lines.push("");
      lines.push(`**Recommendation:** ${issue.recommendation}`);
      lines.push("");
    }
  }

  if (scan.recommendations.length > 0) {
    lines.push(`## Prioritized Recommendations`);
    lines.push("");
    scan.recommendations.forEach((rec, i) => lines.push(`${i + 1}. **[${rec.priority.toUpperCase()}]** ${rec.title}`));
    lines.push("");
  }

  if (scan.dependencyAnalysis) {
    lines.push(`## Dependency Analysis`);
    lines.push("");
    lines.push(`${scan.dependencyAnalysis.totalCount} dependencies analyzed — ${scan.dependencyAnalysis.outdatedCount} outdated, ${scan.dependencyAnalysis.deprecatedCount} deprecated.`);
    if (scan.dependencyAnalysis.truncatedForTransfer) {
      lines.push("");
      lines.push(`_Note: showing ${scan.dependencyAnalysis.dependencies.length} of ${scan.dependencyAnalysis.truncatedFullCount} dependencies in this report; totals above reflect the full analysis._`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by GitPulse. Scores reflect data available at scan time and may become outdated as the project changes._");

  return lines.join("\n");
}
